<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK05RxzC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK05RxzC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK05RxzC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK05RxzC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerK05RxzC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'K05RxzC',
    'container.build_id' => '1079c2eb',
    'container.build_time' => 1624993962,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK05RxzC');
